### ISSUE TITLE
Feature Request: Re-arrange monitors

### ISSUE THREAD

**Issue by 710FarZa** [GeekyEggo/windows-display-settings#16] opened 2023-10-18 04:20 UTC
So i play this game and even in full screen with two monitors my mouse goes to my second monitor. 

So I am looking for a way to setup 2 binds where it will rearrange my display setup so it moves my monitors in the display settings without having to go change it.

Let me know if you have any questions

**Comment by 710FarZa** [comment] 2023-10-18 04:21
what i usually do is rearrange one of my monitors on top of the other and to the side so its a very small pass way

**Comment by GeekyEggo** [comment] 2024-09-03 13:06
Duplicate of #15.

**Closed as not planned by GeekyEggo** 2024-09-03 13:06 UTC
Labels: enhancement
