### ISSUE TITLE
Can't switch back to screen 1920*1080

### ISSUE THREAD

**Issue by Siaomo** [GeekyEggo/windows-display-settings#18] opened 2023-11-23 00:27 UTC
I switched to 1280*960 360hz and it is normal
![image](https://github.com/GeekyEggo/windows-display-settings/assets/78332860/baef1ef2-d39f-4e00-bd75-25373e8685dc)
But when I switch it back to 1920*1080 360HZ, it shows the yellow triangle Golden Detective.
![image](https://github.com/GeekyEggo/windows-display-settings/assets/78332860/e3dea9b7-c532-4892-94d5-89dea31bcd82)
Any plans to repair it?

**Comment by SoyLevelMax** [comment] 2024-04-03 06:23
Same problem here... two weeks ago, was OK... but now, don't work

**Comment by tradaogit** [comment] 2024-04-20 14:59
Same here. Did you guys find how to solve it?

**Comment by deadlydog** [comment] 2024-07-18 03:53
I have the same problem too. #22 looks to be a duplicate of this as well.

**Comment by GeekyEggo** [comment] 2024-09-03 13:03
Thanks for all your patience whilst I look into this — I'm happy to say [v1.2 is now available on Marketplace](https://marketplace.elgato.com/product/windows-display-settings-cb3993d5-9e95-40bd-bb1d-22b3b499f5a7), and introduces a "Scaling Mode" option to the "Resolution" action, allowing you to specify whether to "Stretch" or "Center" your display.

This should hopefully resolve the issue, but please feel free to raise a new ticket if you encounter any problems. 🚀

**Closed as completed by GeekyEggo** 2024-09-03 13:03 UTC

**Comment by deadlydog** [comment] 2024-09-03 21:09
I tested with the new version and still have this same issue, regardless of if I have the `Scaling Mode` set to `Default` or `Stretch`.
